apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 1m # 处理超时时间
      smtp_smarthost: ' smtp.example.com:465' # 邮箱smtp服务器代理
      smtp_from: 'ss@example.com' # 发送邮箱名称
      smtp_auth_username: 'ss@example.com' # 邮箱名称
      smtp_auth_password: '' # 授权密码
      smtp_require_tls: false # 不开启tls 默认开启
 
    receivers:
    - name: Default
      email_configs: # 邮箱配置
      - to: "test.example.com" # 接收警报的email配置
 
    route:
      group_interval: 1m # 在发送新警报前的等待时间
      group_wait: 10s # 最初即第一次等待多久时间发送一组警报的通知 
      receiver: Default
      repeat_interval: 1m # 发送重复警报的周期
type: Opaque
