apiVersion: v1
kind: PersistentVolume
metadata:
  name: granfa-01
  namespace: monitoring
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: granfa-lpv
  local:
    path: /data/prometheus/granfa
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master01
